In [23]:
class COLORS:
    RED = 'red'
    YELLOW = 'yellow'
    GREEN = 'green'
    CYAN = 'cyan'
    MAGENTA = 'magenta'
    BLUE = 'blue'


class SHAPES:
    TRIANGLE = 'triangle'
    DIAMOND = 'diamond'
    SQUARE = 'square'
    CIRCLE = 'circle'
    STAR = 'star'
    SPARKLE = 'sparkle'


class Piece:
    def __init__(self, color=None, shape=None):
        self.color = color
        self.shape = shape

    def __str__(self):
        return '%s %s' % (self.color, self.shape)

    def __repr__(self):
        return self.__str__()

def generate_new_bag_of_tiles():
    print("hello world")
    _bag_of_tiles = []

    shapes = [
        SHAPES.CIRCLE,
        SHAPES.DIAMOND,
        SHAPES.SPARKLE,
        SHAPES.SQUARE,
        SHAPES.STAR,
        SHAPES.TRIANGLE
    ]

    colors = [
        COLORS.BLUE,
        COLORS.CYAN,
        COLORS.GREEN,
        COLORS.MAGENTA,
        COLORS.RED,
        COLORS.YELLOW
    ]

    # for i in range(3):
    for c in range(len(colors)):
        for s in range(len(shapes)):
            _bag_of_tiles.append(Piece(color=colors[c], shape=shapes[s]))    
    return _bag_of_tiles
bag_of_tiles = generate_new_bag_of_tiles()

hello world


In [24]:
bag_of_tiles

[blue circle,
 blue diamond,
 blue sparkle,
 blue square,
 blue star,
 blue triangle,
 cyan circle,
 cyan diamond,
 cyan sparkle,
 cyan square,
 cyan star,
 cyan triangle,
 green circle,
 green diamond,
 green sparkle,
 green square,
 green star,
 green triangle,
 magenta circle,
 magenta diamond,
 magenta sparkle,
 magenta square,
 magenta star,
 magenta triangle,
 red circle,
 red diamond,
 red sparkle,
 red square,
 red star,
 red triangle,
 yellow circle,
 yellow diamond,
 yellow sparkle,
 yellow square,
 yellow star,
 yellow triangle]

In [54]:
look_up_dict = {}
def piece_to_float_convewrter(piece, look_up_dict):
    piece = str(piece)
    if len(look_up_dict) == 36:
        piece_in_float = look_up_dict[piece]
        return piece_in_float
    else:
        float_auxilary = -0.90
        counter = 0
        shapes = [
            SHAPES.CIRCLE,
            SHAPES.DIAMOND,
            SHAPES.SPARKLE,
            SHAPES.SQUARE,
            SHAPES.STAR,
            SHAPES.TRIANGLE
        ]

        colors = [
            COLORS.BLUE,
            COLORS.CYAN,
            COLORS.GREEN,
            COLORS.MAGENTA,
            COLORS.RED,
            COLORS.YELLOW
        ]

        for c in range(len(colors)):
            for s in range(len(shapes)):
                zero_check = round(float_auxilary + (counter * 0.05), 2)
                if zero_check == 0:
                    zero_check = round(zero_check + 0.05, 2)
                    counter += 1
                look_up_dict[str(Piece(color=colors[c], shape=shapes[s]))] = zero_check
                counter += 1
    
        # # print(look_up_dict)
        # # print(type(piece))
        # # Assuming 'look_up_dict' is your dictionary
        # first_key = next(iter(look_up_dict))
        # print(type(first_key))
        print(len(look_up_dict))
        piece_in_float = look_up_dict[str(piece)]
        return piece_in_float
        

In [55]:
piece_to_float_convewrter(str(bag_of_tiles[0]), look_up_dict)

36


-0.9

In [8]:
import numpy as np

grid_length = 5
board = np.zeros((grid_length, grid_length), dtype=np.float32)
board[0][0] = 1
print(board)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
np.all(board == float(0))



False

In [10]:
legal_actions = [0,0,0,0,0]
np.all(legal_actions == 0)

False

In [11]:
legal_actions = [0,0,0,0,0]
np.all(np.array(legal_actions) == 0)

True

In [ ]:
legla